apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-pv
  namespace: codebras
spec:
  capacity:
    storage: 1Gi # Adjust as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
