apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgdata-pv
  namespace: codebras
spec:
  capacity:
    storage: 1Gi  # Specify the size
  accessModes:
    - ReadWriteOnce  # Use ReadWriteOnce for hostPath
  nfs:
    path: /mnt/data/codebras 
    server: nfs-subdir-external-provisioner
  storageClassName: "playlist-storage"
