services:
  playlistdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./20240925.04.46.20.sql:/docker-entrypoint-initdb.d/A_init.sql

  playlistserver:
    build: ./PlaylistApp.Server
    ports:
      - 421:8080
    environment:
      ConnectionStrings__ppdb: user id= postgres; password=postgres; server=playlistdb; database= postgres;
      Client-ID: ""
      Client-Secret: ""
      allowAll: "true"
    depends_on: 
      - playlistdb
      


  playlistclient:
    build: 
      context: ./playlistapp.client
      args:
        VITE_URL: http://localhost:421
    ports:
      - 420:80
    environment:
      VITE_AUTH0_DOMAIN: dev-hto6puiswhque3fr.us.auth0.com
      VITE_AUTH0_CLIENT_ID: ubMKeoY2RUXas6SYMEwlzoX30ByMxpwt
    depends_on: 
      - playlistserver


