apiVersion: v1
kind: PersistentVolume
metadata:
  name: playlist-volume
  namespace: codebras
spec:
  capacity:
    storage: 1Gi  # Specify the size
  accessModes:
    - ReadWriteOnce  # Use ReadWriteOnce for hostPath
  storageClassName: playlist-storage
  hostPath:
    path: /mnt/data/codebras 