apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playlist-ingress
  namespace: codebras
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cert-manager-webhook-duckdns-project-playlist-production
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
  - hosts:
      - projectplaylist.duckdns.org # Frontend Client
      - api.projectplaylist.duckdns.org # Backend Server
    secretName: cert-manager-webhook-duckdns-project-playlist-webhook-tls
  rules:
  - host: projectplaylist.duckdns.org # Main domain for the client
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: playlist-client
            port:
              number: 80
  - host: api.projectplaylist.duckdns.org # Main domain for the client
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: playlist-server
            port:
              number: 8080
