apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: codebras2023@gmail.com  # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - dns01:
        webhook:
            groupName: acme.codebras.com
            solverName: duckdns
            config:
              tokenSecretRef:
                name: duckdns-token
                key: token