apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: codebras  # Specify the namespace here
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: codebras2023@gmail.com  # Replace with your email
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - dns01:
        duckdns:
          tokenSecretRef:
            name: duckdns-secret  # Reference the secret containing your token
            key: token