name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: playlist-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set in your repository secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set in your repository secrets

      - name: Build and push server image
        run: |
          cd ./PlaylistApp.Server

          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/playlistserver:latest \
          -t ${{ secrets.DOCKER_USERNAME }}/playlistserver:${{ github.run_number }} .

          docker push ${{ secrets.DOCKER_USERNAME }}/playlistserver --all-tags

      - name: Build and push client image
        run: |
          cd ./playlistapp.client

          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/playlistclient:latest \
          -t ${{ secrets.DOCKER_USERNAME }}/playlistclient:${{ github.run_number }} .

          docker push ${{ secrets.DOCKER_USERNAME }}/playlistclient --all-tags

      - name: Apply kubernetes
        run: |
          export TAG_ID=${{github.run_number}}

          for file in ./kubernetes/*; do 
            cat $file | envsubst | kubectl apply -f -
          done

    