name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: playlist-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set in your repository secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set in your repository secrets

      - name: Push playlist server
        uses: docker/build-push-action@v2
        with:
          context: ./PlaylistApp.Server  # Path to server Dockerfile
          push: true
          tags: 
            - ${{ secrets.DOCKER_USERNAME }}/playlistserver:latest
            - ${{ secrets.DOCKER_USERNAME }}/playlistserver:${{github.run_number}}

      - name: Push playlist client
        uses: docker/build-push-action@v2
        with:
          context: ./playlistapp.client  # Path to server Dockerfile
          push: true
          tags: 
            - ${{ secrets.DOCKER_USERNAME }}/playlistclient:latest
            - ${{ secrets.DOCKER_USERNAME }}/playlistclient:${{github.run_number}}

      - name: Apply kubernetes
        run: |
          export TAG_NUM=${{github.run_number}}

          for file in ./kubernetes/*; do 
            cat $file | envsubst | /home/ethane/.nix-profile/bin/kubectl apply -f -
          done

    