name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: playlist-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set in your repository secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Set in your repository secrets

      - name: Build and push server image
        uses: docker/build-push-action@v2
        with:
          context: ./PlaylistApp.Server  # Path to server Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/playlistserver:latest

      - name: Build and push client image
        uses: docker/build-push-action@v2
        with:
          context: ./playlistapp.client  # Path to client Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/playlistclient:latest
    